### ISSUE TITLE
can merge a demographic and BIDS representation

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#33] opened 2023-01-09 22:48 UTC

**Comment by alyssadai** [comment] 2023-02-22 23:09
@surchs duplicate of #79 (which is now closed)? 

For some reason this issue didn't show up in the BIDS command epic even though it says you mentioned it. 🤔

**Comment by surchs** [comment] 2023-02-23 18:23
Oh good, let's close it then?

**Closed** 2023-02-23 18:34 UTC
Labels: feature:enhancement, type:feature
