### ISSUE TITLE
Validate that discrete values in data dictionary exist in bagel.tsv

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#112] opened 2023-04-03 16:25 UTC
Protect against:

- I defined a "missing value" but for some odd reason it never gets applied, leading to unexpected outcomes
- I accidentally used the wrong data dictionary for my `bagel.tsv` (see #109)

Sidenote: what happens for things like "Sex" or "Diagnosis" if a value exists in `bagel.tsv` but not in data dictionary? Are we already protected?

Now that we cast everything to string (#108) we need to make sure we don't miss an existing annotation because of that.

**Comment by alyssadai** [comment] 2023-04-05 15:56
Duplicate of #109

**Comment by alyssadai** [comment] 2023-04-05 15:57
Duplicate of #109

**Closed by alyssadai** 2023-04-05 15:57 UTC
Labels: feature:enhancement, type:feature
